# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/golangci/golangci-lint
    rev: v1.55.2
    hooks:
    -   id: golangci-lint

-   repo: local
    hooks:
    -   id: go-fmt
        name: go fmt
        entry: go fmt ./...
        language: system
        pass_filenames: false
    -   id: go-vet
        name: go vet
        entry: go vet ./...
        language: system
        pass_filenames: false
    -   id: go-test
        name: go test
        entry: go test ./...
        language: system
        pass_filenames: false
